### ISSUE TITLE
Handling missing annotations

### ISSUE THREAD

**Issue by zhengli09** [xihaoli/STAAR#12]
Hello Xihao,

Thanks for developing this excellent tool! I've been learning to use the STAAR package to analyze our own dataset. In the analysis, we prepared functional annotations that are most informative for the phenotype of our interest and tried to use those annotations in addition to the ones mentioned in you paper to inform our variant-set analyses. However, we do occasionally come across with missing values in those annotations. I am wondering how missing annotations can be handled within the STAAR pipeline and if you have ever encountered this missing value issue in your analysis? Thank you so much!

Best,
Zheng

**Comment by xihaoli** [comment]
Hi Zheng,

Thanks for your message. If there are missing annotations for some variants, you may impute the annotation values before incorporating them into the STAAR pipeline (for example, by imputing as smallest possible values among all variants with non-missing annotation values). Note that the STAAR pipeline incorporates (numerical) annotations robustly by using its Phred-scaled scores (i.e. based on the rankings). You may want to create the Phred-scaled scores for each annotation based on their raw values before incorporating them into the STAAR pipeline.

Please let me know if you have any additional questions.

Best,
Xihao

**Comment by zhengli09** [comment]
Thank you Xihao! Your suggestion is very helpful.

Best,
Zheng
