### ISSUE TITLE
Calculation of Phred Scores for Functional/Deleterious Annotations

### ISSUE THREAD

**Issue by HasanA75** [xihaoli/STAAR#15]
Hello,

I wanted to confirm that when calculating a Phred score for a continuous-valued annotation, the Phred scores should be calculated so that a higher Phred score indicates higher functionality or deleteriousness. For example, if annotation A indicates higher deleteriousness with a higher annotation value, the Phred score generated for A should have a higher Phred score indicating higher deleteriousness.

**Comment by xihaoli** [comment]
Hi Hasan,

Yes, your understanding is correct. Indeed, if annotation A indicates higher deleteriousness with a higher annotation value, the Phred score generated for A should have a higher Phred score indicating higher deleteriousness. The STAAR framework will then upweight variants with higher Phred scores among all variants in the variant set.

Best,
Xihao

**Comment by HasanA75** [comment]
Hello Xihao,

Thank you for your response. So, based on this, a Phred score generated for A should be positively correlated with the original scores of A, with a higher Phred score for A associated with a higher score for A? And suppose there is an annotation B where deleteriousness or functionality is indicated with lower scores. In that case, higher Phred scores for B should be associated with lower scores for B? 

Thank you again for your help.

**Comment by xihaoli** [comment]
Hi Hasan,

In the case you described, higher Phred scores for A should be associated with higher original scores for A, and higher Phred scores for B should be associated with lower original scores for B. The STAAR framework puts higher weights on variants with higher Phred scores, so users can decide the directionality when calculating Phred scores for a given annotation. Another remark is that neither the values of the original scores nor the Phred scores are used directly as the weights, but the relative ranks are used to ensure that the weighting scheme in STAAR is robust. Mathematically, there is a one-to-one relationship between Phred scores and relative ranks. For more details, please see the Methods section of the [STAAR publication](https://doi.org/10.1038/s41588-020-0676-4).

Best,
Xihao

**Comment by HasanA75** [comment]
Thank you for your help.

Sincerely,
Hasan
