### ISSUE TITLE
Question About Assessing Relative Importance of Tests and Annotations

### ISSUE THREAD

**Issue by HasanA75** [xihaoli/STAAR#16]
Hello Xihao,

I was interested in examining which tests (STAAR-S, STAAR-B, STAAR-A) and annotations are the primary drivers of the overall STAAR p-value generated. I noticed that the paper gives equations for deriving the test statistics from the P-values. I wanted to confirm with you that a good way of assessing the relative importance of each test in determining the overall P-value would be to calculate the components of the test statistic T_{STAAR-O} using STAAR output and comparing the absolute values of the components. I also wanted to confirm with you that a similar method could be used to assess which annotations are most important in driving the P-values generated by STAAR-S, STAAR-B, and STAAR-A by using the formulas for T_{STAAR-S}, T_{STAAR-B} and T_{STAAR-A}. Would there be another way of assessing the relative importance of each test and annotation? Thank you in advance.

Sincerely,
Hasan

**Comment by xihaoli** [comment]
Hi Hasan,

Thanks for your question. Indeed, by combining different types of tests into an omnibus test, STAAR-O has a robust power with respect to the sparsity of causal variants and the directionality of effects of causal variants in a variant set, as well as variant multifacet functions and MAFs. Specifically, by including the burden test, STAAR-O is powerful when most variants in a variant set are causal and have effects in the same direction; by including SKAT, STAAR-O is powerful when not a small number of variants in a variant set are causal with effects in different directions, or when variants in a variant set are in high linkage disequilibrium; by including ACAT-V, STAAR-O is powerful when a small number of variants in a variant set are causal or a good number of extremely rare variants are causal; by weighting each type of tests using multiple annotation principal components and other integrative functional scores and qualitative annotations, STAAR-O is powerful when any of these variant functional annotations can pinpoint causal variants and help boost power.

As illustrated in the [STAAR publication](https://doi.org/10.1038/s41588-020-0676-4), there is a one-to-one relationship between the test statistic and its P-value (for example T_{STAAR-O} vs P_{STAAR-O}; T_{STAAR-S} vs P_{STAAR-S}; T_{STAAR-B} vs P_{STAAR-B}; T_{STAAR-A} vs P_{STAAR-A}). Thus, you may look at the P-values of STAAR-S, STAAR-B, and STAAR-A to assess which specific type of tests (SKAT, burden, or ACAT-V) drive the association signal of STAAR-O. Similarly, you may also look at the annotation-specific P-values within STAAR-S, STAAR-B, and STAAR-A to assess which specific annotations (SKAT, burden, or ACAT-V) drive the association signal. The output of the `STAAR()` function includes P-values weighted by each annotation for each test ([manual](https://github.com/xihaoli/STAAR/blob/master/docs/STAAR_manual.pdf)).

Best,
Xihao
