### ISSUE TITLE
Reference genome version issues"

### ISSUE THREAD

**Issue by johjoon** [xihaoli/STAAR#17]
Dear Professor,

I have encountered a challenge related to reference genome versions during my analysis. I have been using GRCh37, but the FAVOR annotation is based on GRCh38. Do you have any suggestions or recommendations for a more effective solution?

I have attempted to liftover the FAVOR annotation to GRCh37, but it appears to result in the loss of numerous variants' annotation. Unfortunately, I am uncertain about the potential impact of this on the analysis.

I would greatly appreciate your insights and advice.

Thank you.

Best regards.

**Comment by xihaoli** [comment]
Hi @johjoon,

Thanks for reaching out. As your question is directly related to [FAVOR annotation database](https://favor.genohub.org/), please forward your question to the [FAVOR discussion forum](https://discussion.genohub.org/) to get help.

Best,
Xihao
