### ISSUE TITLE
How to generate the genotype file more quickly?

### ISSUE THREAD

**Issue by dylanzhao1993** [xihaoli/STAAR#2]
Dear Sir or Madam,

I am trying to run STAAR using WGS data for about 60k participant. It is easy to use bcftools to extract the genotype data of a specific region for these 60k participants. However, the output is a p*n matrix and the STAAR requires n*p matrix. It's time-consuming to transpose this such large matrix. So I wonder whether you can suggest some more efficient ways to get the required format of genotype files from gVCF file.  

Best wishes,

Yajie Zhao

20/10/2020

**Comment by xihaoli** [comment]
Hi Yajie,
Thanks for your question. It is recommended to consider the Genomic Data Structure (GDS) format for efficient storage and manipulation of WGS data. Here is a document for an [introduction to GDS](https://si.biostat.washington.edu/sites/default/files/modules/GDS_intro_0.pdf). The tutorials of [SeqArray](https://www.bioconductor.org/packages/release/bioc/vignettes/SeqArray/inst/doc/SeqArrayTutorial.html) and [SeqVarTools](https://www.bioconductor.org/packages/release/bioc/vignettes/SeqVarTools/inst/doc/SeqVarTools.pdf) provide functionalities of manipulating GDS files, including transforming VCF file to GDS file using the seqVCF2GDS() function, as well as extracting genotype data of a specific region using the seqSetFilter() and seqGetData() functions in the [SeqArray](https://www.bioconductor.org/packages/release/bioc/html/SeqArray.html) package. The resulting genotype matrix from seqGetData() function is n (sample size) by p (# of variants).
Please feel free to let me know if you have any questions.
Best,
Xihao

**Comment by dylanzhao1993** [comment]
Hi Xihao,

Thank you very much for your prompt reply and useful advice. 

I will read through the introduction of GDS and try to run it. 

Best wishes,

Yajie

**Comment by xihaoli** [comment]
No problem, Yajie. Please feel free to let me know if you have any questions along the way.
Best,
Xihao
