### ISSUE TITLE
ERROR: compilation failed for package ‘STAAR’

### ISSUE THREAD

**Issue by xysj1989** [xihaoli/STAAR#3]
Dear developer,

I'm trying to install STAAR in R 4.0.1, in my MacBook. but I have met some problem. 

Following your instructions, I first install Rcpp and RcppArmadillo, and also imports R packages Rcpp, GMMAT, GENESIS, Matrix.

Then I type: 
library(devtools)
devtools::install_github("xihaoli/STAAR")

However, a error happens:

ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [STAAR.so] Error 1
ERROR: compilation failed for package ‘STAAR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/STAAR’
Error: Failed to install 'STAAR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/k7/938j3spx4tg7b5pznwh12ptc8x4d24/T//RtmpPAnQrm/filef9ffc921464/STAAR_0.9.5.tar.gz’ had non-zero exit status

<img width="484" alt="image" src="https://user-images.githubusercontent.com/13048628/97091566-b2ca0480-160a-11eb-8bc9-f28788e5a4c3.png">

Would you like to give me some suggestion to solve this problem?
Best

**Comment by xihaoli** [comment]
Hi,
Thanks for your question. It seems like there is a missing C++ library for gfortran. Could you please try [download and install gfortran](http://hpc.sourceforge.net/) based on your MacOS version, and then try reinstall the STAAR package?
Please feel free to let me know if you have any questions.
Best,
Xihao

**Comment by xysj1989** [comment]
@xihaoli 

Hello Xihao,

Thank you so much for your reply! The installation problem has been solved following your suggestion, with a simple command "brew cask install gfortran".

My group has got around 2000 Whole exome sequencing data (1000 cancer cases and 1000 controls). Previously, other seniors have applied SKAT (https://www.hsph.harvard.edu/skat/) analysis to try to find some rare variants related to this specific cancer. However, they finally got nothing interesting, and think it maybe limited by such a small sample size. 

Now they suggest me to try your STAAR method. However, when I read your paper published in Nature Genetics, I notice that the sample size in your discovery samples (12,316) and replication samples (17822) are also really big and they are based on Whole genome sequencing data right?

I'm really a newbie to this area. Based on your well experience, do you think our sample size (1000 case / 1000 control) based on WES is big enough for your STAAR analysis?

Best!

**Comment by xihaoli** [comment]
Hi,
Thanks so much for letting me know the STAAR package has been installed successfully.

STAAR works for your sample size (1000 case / 1000 control). Larger sample size will increase power of WES/WGS analysis.

Best,
Xihao
