### ISSUE TITLE
Script for calculation of annotation PCs (aPCs) and source file for annotations

### ISSUE THREAD

**Issue by gchauhan83** [xihaoli/STAAR#4]
Dear Xihao,

Is it possible to have a script that will do all the 5 steps (step-0 to step-4) as mentioned in http://favor.genohub.org/.
This will be helpful for common users.

The batch download at "favor" does not allow download of annotations for more than 10K variants. Can this limit be increased or a source file with all the annotations be made available just like the list of variants from TOPMed in the Bravo server. The annotation data can be part of the INFO column in the vcf format. This again is important if large scale studies are to use your resources in a timely fashion.

Thanks for this wonderful tool.

Best
Ganesh

**Comment by xihaoli** [comment]
Hi Ganesh,

Thanks so much for your question about FAVOR. Could you please contact FAVOR development team [via email](mailto:hzhou@hsph.harvard.edu,tarapoglou@hsph.harvard.edu,xihaoli@g.harvard.edu,li@hsph.harvard.edu) to have a detailed discussion on your question and request?

Best,
Xihao
