### ISSUE TITLE
decomposition failed error

### ISSUE THREAD

**Issue by prnakka** [xihaoli/STAAR#5]
Hi, Thanks for making STAAR so easy to install and use! I am trying to run Staar on a test dataset of 5000 individuals for one chromosome and I get the following error when I try to run the STAAR() function: 

error: eig_sym(): decomposition failed
Error in STAAR_O_SMMAT(G, P, residuals.phenotype, weights_B = w_B, weights_S = w_S,  : 
  eig_sym(): decomposition failed

Any thoughts on how to resolve this error would be greatly appreciated, thanks!!

**Comment by xihaoli** [comment]
Hi Priya,
Thanks for your question. In `STAAR()`, the `eig_sym()` is a [c++ function](http://arma.sourceforge.net/docs.html#eig_sym) embedded in the Armadillo library that performs eigen-decomposition of the underlying dense symmetric matrix (in this case, the weighted covariance matrix). May I ask what would be the dimension for your eigen-decomposition, i.e. what is the dimension of the `G` matrix (you may follow [lines 76-102 in the `STAAR()` function](https://github.com/xihaoli/STAAR/blob/master/R/STAAR.R) to obtain this `G` matrix from the `genotype` matrix)?
Best,
Xihao

**Comment by prnakka** [comment]
Hi, The dimension of the G matrix I was running this function on was 4620 x 285.  Thanks, Priya

**Comment by xihaoli** [comment]
Hi Priya,
Thanks for your reply. The dimension of your `G` matrix is manageable for `STAAR()` function. In this case, could you please check whether your `G` matrix or annotation weights, i.e. `w_B`, `w_S`, `w_A`, contain any missing values? If not, could you please try updating your `Rcpp` and `RcppArmadillo` packages to the latest version and try it again?
Best,
Xihao

**Comment by prnakka** [comment]
Hello, Removing variants with missing values in the annotations fixed the problem for me, thank you so much!! I had one last question: is there a method you would recommend to combine STAAR p-values across multiple studies? Thank you again!

**Comment by xihaoli** [comment]
Hi Priya,

Thanks so much for letting me know that the problem has been fixed. For your question on combining STAAR p-values, could you please send us an [email](mailto:xihaoli@g.harvard.edu,li@hsph.harvard.edu) to have a further discussion, as it may depend on the specific study design of your project?

Thanks again.

Best,
Xihao
