### ISSUE TITLE
docker image of STAAR

### ISSUE THREAD

**Issue by pirocv** [xihaoli/STAAR#6]
Dear developer,

Thank you very much providing such a wonderful software.
I'm interested in STAAR software and would like to use it in my server.

However, the problem is that our server is a stand-alone (offline) server, so I'm having a hard time installing it (due to dependencies and devtools).
I'd appreciate it if you could provide a docker image of STAAR software.

Thanks in advance.

**Comment by xihaoli** [comment]
Hi,
Hope your problem has been resolved. In any case, we can provide an offline version of the STAAR package with all dependencies and devtools so that you can install from source.
If the problem still remains, we can try to provide a docker image of STAAR software.
Thank you very much.
Best,
Xihao
