### ISSUE TITLE
 How to simply use vcf format file as input

### ISSUE THREAD

**Issue by George-du** [xihaoli/STAAR#7]
Hi xi hao,
     I  want to analysis rare variants in my research, and I found your paper published on Nature Genetics.So I want to attempt your method for my data, but I can't implement it quickly. I read your example for using  STAAR(
https://htmlpreview.github.io/?https://github.com/xihaoli/STAAR/blob/master/docs/STAAR_vignette.html), but I found that _fit_null_glm(Y~X1+X2)_  is for each position (or SNP sets) rather than whole genotype dosage matrix，
So what should I do to apply it on my whole genotype dosage matrix that contains missing genotype(NA) quickly?
Can you give me some detailed examples or suggestions?

I am looking forward to your reply.
Best,
Du

**Comment by xihaoli** [comment]
Hi Du,
Thanks for your interest in STAAR. For your question, we want to clarify that the step of _fit_null_glm(Y~X1+X2)_ is for fitting the null model, where no genotype information (i.e. dosage matrix) is involved. After the null model is fitted, STAAR then tests for association between each variant set (e.g. a gene category or a sliding window) and the phenotype of interest.

If you need any further assistance, please feel free to send us an [email](mailto:xihaoli@g.harvard.edu,li@hsph.harvard.edu). Thanks!

Best,
Xihao

**Comment by xihaoli** [comment]
No problem, Du. Please feel free to let me know if you have any questions along the way.
Best,
Xihao
